### ISSUE TITLE
Object drifting

### ISSUE THREAD

**Issue by lessthanzero** [CopenhagenGameCollective/UniMove#10]
Is it possible to remove/reduce the drift of the object on scene? Or is it a hardware problem which cannot be solved programmatically? What causes the drift?

**Comment by thp** [comment]
Which example do you mean? The drift probably happens because the example does not take the accelerometer + magnetometer into account (or not enough) and mostly uses the gyroscope for orientation, which always drifts (that's something all gyroscopes do).
