### ISSUE TITLE
Error: expected 64 bit architecture, but was IMAGE_FILE_MACHINE_I386

### ISSUE THREAD

**Issue by PolGraphic** [CopenhagenGameCollective/UniMove#11]
I've tried to load the sample scene from http://www.copenhagengamecollective.org/projects/unimove/

I get (Unity 5.0.1): `Failed to load 'Assets/Plugins/libpsmoveapi.dll', expected 64 bit architecture (IMAGE_FILE_MACHINE_AMD64), but was IMAGE_FILE_MACHINE_I386.`.

I could not find other (x64) version of `libpsmoveapi.dll`.

I work on Windows 8 x64.

**Comment by thijmensjf** [comment]
Hello,

I am experiencing the same problem. Did you already find a solution or still waiting for an answer?

**Comment by PolGraphic** [comment]
The problem was caused by x32 build of the `libpsmoveapi.dll` You have to build it from sources in `x64

**Comment by thp** [comment]
I guess this can be closed then? Please reopen if you are still experiencing issues.
