### ISSUE TITLE
Unity crashes after pressing play

### ISSUE THREAD

**Issue by hazem17** [CopenhagenGameCollective/UniMove#12]
after i press play unity crashes, i think the problem in the Init function in the UniMoveController.cs script
specifically in the line if(handle == IntPtr.Zero) return false;
if i skipped this line it runs but gives connected devices equal to zero
i use widows 8.1 64bit and unity 5 32bit and tried the project on unity 4 pro but it gives the same error
can you help me
thanks

**Comment by pjarnfelt** [comment]
UniMove is not supporting Windows. Sorry.

tir. 8. mar. 2016 kl. 13.27 skrev Hazem Nizar <notifications@github.com>:

**Comment by hazem17** [comment]
But it says on there page that it supports windows 
http://www.copenhagengamecollective.org/projects/unimove/

**Comment by pjarnfelt** [comment]
We will clarify on that page what is meant by this. It can work if you are lucky, but we cannot officially support it. There are too many issues with the binaries and the bluetooth connectivity on windows.
