### ISSUE TITLE
updating psmoveapi

### ISSUE THREAD

**Issue by ccoenen** [CopenhagenGameCollective/UniMove#6]
The packaged psmoveapi is almost two years old, i am trying to build the current master for use with unimove. I'd like to know if you compiled the files yourselves, or if these are the provided binaries from psmoveapi.

**Comment by ccoenen** [comment]
I updadet the build instructions for windows, and the build seems fine for x86 (can't test x64 for lack of webcam driver). I also can't test the OSX-Build. But would you be interested in a pull request containing binaries?

**Comment by pjarnfelt** [comment]
We will update the library with the newest binaries from the psmoveapi together with some updated features for tracking with a camera very soon.
